In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from pandas import read_csv
from sklearn.linear_model import LinearRegression

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving loan_small.csv to loan_small (1).csv


In [ ]:
df = read_csv('loan_small (1).csv')

In [ ]:
df

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0   LP001002     NaN           5849.0                0.0         NaN  urban   
1   LP001003    Male           4583.0                NaN       128.0   semi   
2   LP001005    Male           3000.0                0.0        66.0    NaN   
3   LP001006  Female           2583.0             2358.0       120.0   semi   
4   LP001008    Male              NaN                0.0       141.0  urban   
5   LP001011    Male           5417.0             4196.0       267.0   semi   
6   LP001013    Male           2333.0             1516.0         NaN  rural   
7   LP001014  Female           3036.0             2504.0       158.0   semi   
8   LP001018    Male           4006.0             1526.0       168.0  rural   
9   LP001020    Male          12841.0            10968.0       349.0   semi   
10  LP001024  Female           3200.0              700.0        70.0  urban   
11  LP001027    Male           2500.0             1840.0       109.0  urban   
12  LP001028  Female              NaN             8106.0         NaN  urban   
13  LP001029    Male           1853.0             2840.0       114.0  urban   
14  LP001030    Male           1299.0             1086.0        17.0   semi   
15  LP001032    Male           4950.0                0.0       125.0   semi   

   Loan_Status  
0            Y  
1            N  
2            Y  
3          NaN  
4            Y  
5            Y  
6            Y  
7            N  
8            Y  
9            N  
10           Y  
11           Y  
12           Y  
13           N  
14           Y  
15           Y

In [ ]:
df_copy = df.copy

In [ ]:
df_copy

<bound method NDFrame.copy of      Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0   LP001002     NaN           5849.0                0.0         NaN  urban   
1   LP001003    Male           4583.0                NaN       128.0   semi   
2   LP001005    Male           3000.0                0.0        66.0    NaN   
3   LP001006  Female           2583.0             2358.0       120.0   semi   
4   LP001008    Male              NaN                0.0       141.0  urban   
5   LP001011    Male           5417.0             4196.0       267.0   semi   
6   LP001013    Male           2333.0             1516.0         NaN  rural   
7   LP001014  Female           3036.0             2504.0       158.0   semi   
8   LP001018    Male           4006.0             1526.0       168.0  rural   
9   LP001020    Male          12841.0            10968.0       349.0   semi   
10  LP001024  Female           3200.0              700.0        70.0  urban   
11  LP001027    Male  

In [ ]:
df.shape

(16, 7)

In [ ]:
df.columns

Index(['Loan_ID', 'Gender', 'ApplicantIncome', 'CoapplicantIncome',
       'LoanAmount', 'Area', 'Loan_Status'],
      dtype='object')

In [ ]:
df.head()

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0  LP001002     NaN           5849.0                0.0         NaN  urban   
1  LP001003    Male           4583.0                NaN       128.0   semi   
2  LP001005    Male           3000.0                0.0        66.0    NaN   
3  LP001006  Female           2583.0             2358.0       120.0   semi   
4  LP001008    Male              NaN                0.0       141.0  urban   

  Loan_Status  
0           Y  
1           N  
2           Y  
3         NaN  
4           Y

In [ ]:
df.tail()

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
11  LP001027    Male           2500.0             1840.0       109.0  urban   
12  LP001028  Female              NaN             8106.0         NaN  urban   
13  LP001029    Male           1853.0             2840.0       114.0  urban   
14  LP001030    Male           1299.0             1086.0        17.0   semi   
15  LP001032    Male           4950.0                0.0       125.0   semi   

   Loan_Status  
11           Y  
12           Y  
13           N  
14           Y  
15           Y

In [ ]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount
count        14.000000          15.000000   13.000000
mean       4103.571429        2509.333333  140.923077
std        2858.096481        3147.982090   86.032418
min        1299.000000           0.000000   17.000000
25%        2520.750000         350.000000  109.000000
50%        3118.000000        1526.000000  125.000000
75%        4858.250000        2672.000000  158.000000
max       12841.000000       10968.000000  349.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            16 non-null     object 
 1   Gender             15 non-null     object 
 2   ApplicantIncome    14 non-null     float64
 3   CoapplicantIncome  15 non-null     float64
 4   LoanAmount         13 non-null     float64
 5   Area               15 non-null     object 
 6   Loan_Status        15 non-null     object 
dtypes: float64(3), object(4)
memory usage: 1.0+ KB


In [ ]:
df.isnull()

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0     False    True            False              False        True  False   
1     False   False            False               True       False  False   
2     False   False            False              False       False   True   
3     False   False            False              False       False  False   
4     False   False             True              False       False  False   
5     False   False            False              False       False  False   
6     False   False            False              False        True  False   
7     False   False            False              False       False  False   
8     False   False            False              False       False  False   
9     False   False            False              False       False  False   
10    False   False            False              False       False  False   
11    False   False            False              False       False  False   
12    False   False             True              False        True  False   
13    False   False            False              False       False  False   
14    False   False            False              False       False  False   
15    False   False            False              False       False  False   

    Loan_Status  
0         False  
1         False  
2         False  
3          True  
4         False  
5         False  
6         False  
7         False  
8         False  
9         False  
10        False  
11        False  
12        False  
13        False  
14        False  
15        False

In [ ]:
df.isnull().sum()

Loan_ID              0
Gender               1
ApplicantIncome      2
CoapplicantIncome    1
LoanAmount           3
Area                 1
Loan_Status          1
dtype: int64

In [ ]:
df1 = df.dropna()

In [ ]:
df1

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
5   LP001011    Male           5417.0             4196.0       267.0   semi   
7   LP001014  Female           3036.0             2504.0       158.0   semi   
8   LP001018    Male           4006.0             1526.0       168.0  rural   
9   LP001020    Male          12841.0            10968.0       349.0   semi   
10  LP001024  Female           3200.0              700.0        70.0  urban   
11  LP001027    Male           2500.0             1840.0       109.0  urban   
13  LP001029    Male           1853.0             2840.0       114.0  urban   
14  LP001030    Male           1299.0             1086.0        17.0   semi   
15  LP001032    Male           4950.0                0.0       125.0   semi   

   Loan_Status  
5            Y  
7            N  
8            Y  
9            N  
10           Y  
11           Y  
13           N  
14           Y  
15           Y

In [ ]:
data_array = df1.values

In [ ]:
data_array

array([['LP001011', 'Male', 5417.0, 4196.0, 267.0, 'semi', 'Y'],
       ['LP001014', 'Female', 3036.0, 2504.0, 158.0, 'semi', 'N'],
       ['LP001018', 'Male', 4006.0, 1526.0, 168.0, 'rural', 'Y'],
       ['LP001020', 'Male', 12841.0, 10968.0, 349.0, 'semi', 'N'],
       ['LP001024', 'Female', 3200.0, 700.0, 70.0, 'urban', 'Y'],
       ['LP001027', 'Male', 2500.0, 1840.0, 109.0, 'urban', 'Y'],
       ['LP001029', 'Male', 1853.0, 2840.0, 114.0, 'urban', 'N'],
       ['LP001030', 'Male', 1299.0, 1086.0, 17.0, 'semi', 'Y'],
       ['LP001032', 'Male', 4950.0, 0.0, 125.0, 'semi', 'Y']],
      dtype=object)

In [ ]:
x = data_array[:,2:5]

In [ ]:
x

array([[5417.0, 4196.0, 267.0],
       [3036.0, 2504.0, 158.0],
       [4006.0, 1526.0, 168.0],
       [12841.0, 10968.0, 349.0],
       [3200.0, 700.0, 70.0],
       [2500.0, 1840.0, 109.0],
       [1853.0, 2840.0, 114.0],
       [1299.0, 1086.0, 17.0],
       [4950.0, 0.0, 125.0]], dtype=object)

In [ ]:
y = data_array[:,-1]

In [ ]:
y

array(['Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25, random_state=0)

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_train[0])
print(y_train[0])

(6, 3)
(6,)
[3200.0 700.0 70.0]
Y


In [ ]:
#knn classifier
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,
                                  p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred_knn = classifier.predict(x_test)

In [ ]:
y_pred_knn

array(['Y', 'Y', 'Y'], dtype=object)

In [ ]:
#cm for knn
from sklearn.metrics import confusion_matrix
cm_knn = confusion_matrix(y_test, y_pred_knn)

In [ ]:
cm_knn

array([[0, 1],
       [0, 2]])

In [ ]:
#svm classifier
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train, y_train)

SVC()

In [ ]:
Y_predict_svm = svc.predict(x_test)

In [ ]:
#cm for svm
from sklearn.metrics import confusion_matrix
cm_svm = confusion_matrix(y_test, Y_predict_svm)

In [ ]:
cm_svm

array([[0, 1],
       [0, 2]])