In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
data = files.upload()

Saving 01Exercise1.csv to 01Exercise1.csv


In [ ]:
df = pd.read_csv('01Exercise1.csv')

In [ ]:
df

gender married   ch  income  loanamt status
0      Male      No  1.0    5849      NaN      Y
1      Male     Yes  1.0    4583    128.0      N
2      Male     Yes  1.0    3000     66.0      Y
3      Male     Yes  1.0    2583    120.0      Y
4      Male      No  1.0    6000    141.0      Y
..      ...     ...  ...     ...      ...    ...
609  Female      No  1.0    2900     71.0      Y
610    Male     Yes  1.0    4106     40.0      Y
611    Male     Yes  1.0    8072    253.0      Y
612    Male     Yes  1.0    7583    187.0      Y
613  Female      No  0.0    4583    133.0      N

[614 rows x 6 columns]

In [ ]:
data_copy = data.copy()

In [ ]:
data_copy

{'01Exercise1.csv': b'gender,married,ch,income,loanamt,status\r\nMale,No,1,5849,,Y\r\nMale,Yes,1,4583,128,N\r\nMale,Yes,1,3000,66,Y\r\nMale,Yes,1,2583,120,Y\r\nMale,No,1,6000,141,Y\r\nMale,Yes,1,5417,267,Y\r\nMale,Yes,1,2333,95,Y\r\nMale,Yes,0,3036,158,N\r\nMale,Yes,1,4006,168,Y\r\nMale,Yes,1,12841,349,N\r\nMale,Yes,1,3200,70,Y\r\nMale,Yes,1,2500,109,Y\r\nMale,Yes,1,3073,200,Y\r\nMale,No,1,1853,114,N\r\nMale,Yes,1,1299,17,Y\r\nMale,No,1,4950,125,Y\r\nMale,No,,3596,100,Y\r\nFemale,No,0,3510,76,N\r\nMale,Yes,1,4887,133,N\r\nMale,Yes,1,2600,115,Y\r\nMale,Yes,0,7660,104,N\r\nMale,Yes,1,5955,315,Y\r\nMale,Yes,0,2600,116,N\r\n,Yes,0,3365,112,N\r\nMale,Yes,,3717,151,N\r\nMale,Yes,1,9560,191,Y\r\nMale,Yes,1,2799,122,Y\r\nMale,Yes,1,4226,110,Y\r\nMale,No,1,1442,35,N\r\nFemale,No,1,3750,120,Y\r\nMale,Yes,,4166,201,N\r\nMale,No,1,3167,74,N\r\nMale,No,1,4692,106,N\r\nMale,Yes,1,3500,114,Y\r\nMale,No,1,12500,320,N\r\nMale,Yes,1,2275,,Y\r\nMale,Yes,0,1828,100,N\r\nFemale,Yes,1,3667,144,Y\r\nMale,No,

In [ ]:
df.shape

(614, 6)

In [ ]:
df.columns

Index(['gender', 'married', 'ch', 'income', 'loanamt', 'status'], dtype='object')

In [ ]:
df.head()

gender married   ch  income  loanamt status
0   Male      No  1.0    5849      NaN      Y
1   Male     Yes  1.0    4583    128.0      N
2   Male     Yes  1.0    3000     66.0      Y
3   Male     Yes  1.0    2583    120.0      Y
4   Male      No  1.0    6000    141.0      Y

In [ ]:
df.tail()

gender married   ch  income  loanamt status
609  Female      No  1.0    2900     71.0      Y
610    Male     Yes  1.0    4106     40.0      Y
611    Male     Yes  1.0    8072    253.0      Y
612    Male     Yes  1.0    7583    187.0      Y
613  Female      No  0.0    4583    133.0      N

In [ ]:
df.describe()

ch        income     loanamt
count  564.000000    614.000000  592.000000
mean     0.842199   5403.459283  146.412162
std      0.364878   6109.041673   85.587325
min      0.000000    150.000000    9.000000
25%      1.000000   2877.500000  100.000000
50%      1.000000   3812.500000  128.000000
75%      1.000000   5795.000000  168.000000
max      1.000000  81000.000000  700.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   gender   601 non-null    object 
 1   married  611 non-null    object 
 2   ch       564 non-null    float64
 3   income   614 non-null    int64  
 4   loanamt  592 non-null    float64
 5   status   614 non-null    object 
dtypes: float64(2), int64(1), object(3)
memory usage: 28.9+ KB


In [ ]:
df.isnull()

gender  married     ch  income  loanamt  status
0     False    False  False   False     True   False
1     False    False  False   False    False   False
2     False    False  False   False    False   False
3     False    False  False   False    False   False
4     False    False  False   False    False   False
..      ...      ...    ...     ...      ...     ...
609   False    False  False   False    False   False
610   False    False  False   False    False   False
611   False    False  False   False    False   False
612   False    False  False   False    False   False
613   False    False  False   False    False   False

[614 rows x 6 columns]

In [ ]:
df.isnull().sum()

gender     13
married     3
ch         50
income      0
loanamt    22
status      0
dtype: int64

In [ ]:
df1 = df.drop('ch',axis=1)

In [ ]:
df1

gender married  income  loanamt status
1      Male     Yes    4583    128.0      N
2      Male     Yes    3000     66.0      Y
3      Male     Yes    2583    120.0      Y
4      Male      No    6000    141.0      Y
5      Male     Yes    5417    267.0      Y
..      ...     ...     ...      ...    ...
609  Female      No    2900     71.0      Y
610    Male     Yes    4106     40.0      Y
611    Male     Yes    8072    253.0      Y
612    Male     Yes    7583    187.0      Y
613  Female      No    4583    133.0      N

[577 rows x 5 columns]

In [ ]:
#dealing with the missing value
#gender = (13/614)*100  = 2.1172
#married = (3/614)*100 = 0.4886
#ch = 8.1433
#loanamt = 3.583

In [ ]:
df2 = df1.dropna()

 FEATURE IMPORTANCE
#to predict the loan status i feel the domain importantly demands the independent variable, gender, married, loanamt so im going to deal those variables in this research, but im not that confident with the ch

In [ ]:
df2

gender married  income  loanamt status
1      Male     Yes    4583    128.0      N
2      Male     Yes    3000     66.0      Y
3      Male     Yes    2583    120.0      Y
4      Male      No    6000    141.0      Y
5      Male     Yes    5417    267.0      Y
..      ...     ...     ...      ...    ...
609  Female      No    2900     71.0      Y
610    Male     Yes    4106     40.0      Y
611    Male     Yes    8072    253.0      Y
612    Male     Yes    7583    187.0      Y
613  Female      No    4583    133.0      N

[577 rows x 5 columns]

In [ ]:
df2.shape

(577, 5)

In [ ]:
df_array = df2.values

In [ ]:
df_array

array([['Male', 'Yes', 4583, 128.0, 'N'],
       ['Male', 'Yes', 3000, 66.0, 'Y'],
       ['Male', 'Yes', 2583, 120.0, 'Y'],
       ...,
       ['Male', 'Yes', 8072, 253.0, 'Y'],
       ['Male', 'Yes', 7583, 187.0, 'Y'],
       ['Female', 'No', 4583, 133.0, 'N']], dtype=object)

In [ ]:
x = df_array[:,2:4]

In [ ]:
x

array([[4583, 128.0],
       [3000, 66.0],
       [2583, 120.0],
       ...,
       [8072, 253.0],
       [7583, 187.0],
       [4583, 133.0]], dtype=object)

In [ ]:
y = df_array[:,-1]

In [ ]:
y

array(['N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y',
       'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'N',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'N', 'N', 'Y', 'Y', 'N',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y',
       'N', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'N',
       'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred_knn = classifier.predict(x_test)

In [ ]:
y_pred_knn

array(['Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y',
       'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'Y'], dtype=object)

In [ ]:
#cm for knn
from sklearn.metrics import confusion_matrix
cm_knn = confusion_matrix(y_test, y_pred_knn)

In [ ]:
cm_knn

array([[ 8, 39],
       [12, 86]])

In [ ]:
#svm classifier
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train, y_train)

SVC()

In [ ]:
Y_predict_svm = svc.predict(x_test)

In [ ]:
#cm for svm
from sklearn.metrics import confusion_matrix
cm_svm = confusion_matrix(y_test, Y_predict_svm)

In [ ]:
cm_svm

array([[ 0, 47],
       [ 0, 98]])